### ISSUE TITLE
Question on ncr model

### ISSUE THREAD

**Issue by crazyfat** [bmxitalia/NCRProject#1]
Hello,
I have a question about your nets.py file.
In your process of converting 𝑒𝑢1∧𝑒𝑢2∧𝑒𝑢3⟹𝑒𝑢4 to ¬𝑒𝑢1∨¬𝑒𝑢2∨¬𝑒𝑢3∨𝑒𝑢4, your left_side_events does not seem to have passed through the NOT neural module. But I look at the "Neural Collaborative Reasoning" author's code, and at line 148 of his NCR.py file, there is an operation that goes through the NOT neural module. 
Is it my misunderstanding about your code? Please answer me.

**Comment by tommasocarraro** [comment]
Hi @crazyfat,
thank you for your interest in my implementation of Neural Collaborative Reasoning!

It is an interesting question!

In order to answer your question, it is easier to make an example. In this example, we assume that the user at index 4 has interacted with the items at indexes 5, 4, 3, 7, 6, 11, with feedbacks 1, 0, 1, 1, 0, 1. We assume that these interactions are ordered by timestamp. From now, I use the notation e_u_i to represent the event vector of user u and item i.

Based on the interactions of user 4 in this example, NCR should construct the following (positive) logical expression:

e_4_5 ∧ ¬e_4_4 ∧ e_4_3 ∧ e_4_7 ∧ ¬e_4_6 ⟹ e_4_11

By applying some reformulation (i.e., material implication and De Morgan's laws), the final logical expression implemented by NCR is:

¬e_4_5 ∨ ¬¬e_4_4 ∨ ¬e_4_3 ∨ ¬e_4_7 ∨ ¬¬e_4_6 ∨ e_4_11

Now, I explain how my implementation reaches this final formula.

Based on the parameter _remove_double_not_, explained in line 19 of my nets.py file, two semantically equal but syntactically different logical expressions could be generated by my implementation. This parameter simply avoids the computation of double negations, in the sense that if, for example, we have ¬¬e_4_4, instead of passing the event vector e_4_4 two times through the NOT module, it does not pass it since e_4_4 is semantically equal to ¬¬e_4_4. In the original NCR implementation, there is no possibility to choose if to remove the double negations.

Now that I have explained the _remove_double_not_ parameter, I can finally answer your question. Let's see step by step how my implementation works:

1. the embeddings of user 4 and items 5, 4, 3, 7, 6, 11 are taken from an embedding matrix. Here, we use the notation emb_u_4 to denote the embedding of user 4 and emb_i_5 to denote the embedding of item 5;
2. event vectors are generated by an encoder network. If we call this network f, then we have:
       - f(emb_u_4, emb_i_5) = e_4_5;
       - f(emb_u_4, emb_i_4) = e_4_4;
       - f(emb_u_4, emb_i_3) = e_4_3;
       - f(emb_u_4, emb_i_7) = e_4_7;
       - f(emb_u_4, emb_i_6) = e_4_6;
       - f(emb_u_4, emb_i_11) = e_4_11.
So, the network f has generated the event vectors that we need for constructing the final logical expression;
3. Now, we have to distinguish two parts of the logical expression. The part at the left side of implication, which contains the "history" of user 4 (composed by items 5, 4, 3, 7, 6), and the part at the right side of implication, which contains the item that we want to predict (item 11). In order to efficiently obtain the left side part, NCR firstly negates all the event vectors in the "history" and then selects if to use the non-negated or negated event vectors based on the user's feedbacks, that are 1, 0, 1, 1, 0 in this example. 
In other words, we have:
       - positive event vectors: e_4_5, e_4_4, e_4_3, e_4_7, e_4_6
       - negated event vectors: ¬e_4_5, ¬e_4_4, ¬e_4_3, ¬e_4_7, ¬e_4_6
       - user's feedback vector: 1, 0, 1, 1, 0
We use the feedback vector as a mask to construct the correct user's history. A 1 in the feedback vector means that we have to take the positive event vector, instead a 0 means that we have to take the negated event_vector. So, after this step, the user's history becomes e_4_5, ¬e_4_4, e_4_3, e_4_7, ¬e_4_6 (if _remove_double_not_ is set to _False_ (line 248)). If, instead, _remove_double_not_ is set to _True_ (line 246), the final history will be ¬e_4_5, e_4_4, ¬e_4_3, ¬e_4_7, e_4_6 (the opposite of the other). We will understand in the next step the reason of this choice;
4. Now, we need to perform the logical OR between the items on the left side of the implication. If _remove_double_not_ is set to _False_, my implementation computes the negation of the event vectors before computing the disjunction (line 259). If, instead, _remove_double_not_ is set to _True_, it is not necessary to compute the negation before the disjunction. So, based on the value of the parameter _remove_double_not_, we end up with the following two possibilities:
      - ¬e_4_5 ∨ ¬¬e_4_4 ∨ ¬e_4_3 ∨ ¬e_4_7 ∨ ¬¬e_4_6 (_remove_double_not_ is set to _False_);
      - ¬e_4_5 ∨ e_4_4 ∨ ¬e_4_3 ∨ ¬e_4_7 ∨ e_4_6 (_remove_double_not_ is set to _True_).
Note that these two logical expressions are logically equivalent. I hope you have understood the use of the _remove_double_not_ parameter;
5. In the last step, the disjunction between the left side of implication and the right side of implication is computed. We will end up with two possibilities based on the value of the parameter _remove_double_not_:
      - ¬e_4_5 ∨ ¬¬e_4_4 ∨ ¬e_4_3 ∨ ¬e_4_7 ∨ ¬¬e_4_6 ∨ e_4_11 (value is set to _False_);
      - ¬e_4_5 ∨ e_4_4 ∨ ¬e_4_3 ∨ ¬e_4_7 ∨ e_4_6 ∨ e_4_11 (value is set to _True_).

I hope I have answered your question!

Thanks again!

**Comment by crazyfat** [comment]
This is really an ingenious design.！

Thank you for your examples and careful answers.

**Comment by tommasocarraro** [comment]
Thank you for your kind words!
